#ifndef SONGIMPORTERLIB_GLOBAL_H
#define SONGIMPORTERLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SONGIMPORTERLIB_LIBRARY)
#define SONGIMPORTERLIB_EXPORT Q_DECL_EXPORT
#else
#define SONGIMPORTERLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // SONGIMPORTERLIB_GLOBAL_H
